sonar.projectKey=andryraveloarison_savia
sonar.organization=andryraveloarison
sonar.projectName=Savia Backend
sonar.projectVersion=1.1.0

# Paths*
sonar.exclusions=app/tests/**
sonar.sources=app
sonar.tests=app/tests
sonar.python.version=3.12

# Coverage
sonar.python.coverage.reportPaths=coverage/coverage.xml

# Language
sonar.language=python
sonar.sourceEncoding=UTF-8
